version: "3.8"

services:
  database:
    container_name: "${APP_NAME}_database"
    image: mysql:5.7
    ports:
      - "${LOCAL_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
    restart: on-failure:5

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   depends_on:
  #     - database
  #   environment:
  #     - PMA_ARBITRARY=1
  #     - PMA_HOSTS=database
  #     - PMA_USER=wordpress
  #     - PMA_PASSWORD=wordpress
  #   ports:
  #     - "5000:80"
  #   volumes:
  #     - ./docker/phpmyadmin/sessions:/sessions

  wordpress:
    container_name: "${APP_NAME}_wordpress"
    build: ./php
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./public:/var/www/html
    ports:
      - "${LOCAL_SERVER_PORT}:80"
    depends_on:
      - database
    environment:
      WP_DIR: ${WP_DIR}
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_TABLE_PREFIX: wp_
      VIRTUAL_HOST: ${APP_NAME}.zeroyon-preview.com
    working_dir: /var/www/html${WP_DIR}
    restart: on-failure:5
    networks:
      - default
      - nginx-proxy

  cli:
    image: wordpress:cli
    container_name: "${APP_NAME}_cli"
    volumes_from:
      - wordpress
    volumes:
      - ./wp-install.sh:/tmp/wp-install.sh
    depends_on:
      - database
      - wordpress
    command: --info
    user: xfs
    environment:
      WORDPRESS_DB_HOST: database:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      LOCAL_SERVER_PORT: ${LOCAL_SERVER_PORT}
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      WP_DIR: ${WP_DIR}
      THEME_NAME: ${THEME_NAME}

  wordmove:
    depends_on:
      - wordpress
    image: welaika/wordmove
    container_name: "${APP_NAME}_wordmove"
    working_dir: /home
    volumes:
      - ./Movefile.yml:/home/Movefile.yml
      - ./public:/var/www/html
      - ./.ssh-keys:/home/.ssh
    env_file: .env
    environment:
      LANG: C.UTF-8

  # mailhog:
  #   image: mailhog/mailhog
  #   ports:
  #     - 1025:1025
  #     - 8025:8025

networks:
  nginx-proxy:
    external: true
    name: nginx-proxy-network
